### ISSUE TITLE
Clean up UI on Icons tab

### ISSUE THREAD

**Issue by Danieltsang** [aaptiv/design-docs#4]

**Comment by odmln** [comment]
@Danieltsang I think I need to rebuild this page, some of the props are outdated from the old site we pulled the code from. Also, none of the filled icons are loading, guessing thats just cause on line:28 we source the icons from the /outlined folder only. Let's chat about this during our next meeting. 

Lastly, I'll need to sync with Wendkos about icon direction moving forward, we should try and get the most up-to-date icons loaded into this repo.

**Comment by Danieltsang** [comment]
@odmln I fixed the issue with filled icons not loading. They were loading properly but they were just hidden because of CSS.
